///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SafeRailwayProject.Actions.Login.Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyUserLoginSuccessfully recording.
    /// </summary>
    [TestModule("990af605-efaf-4fce-b153-b28c2999da9c", ModuleType.Recording, 1)]
    public partial class VerifyUserLoginSuccessfully : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SafeRailwayProject.Repository.SafeRailwayProjectRepository repository.
        /// </summary>
        public static global::SafeRailwayProject.Repository.SafeRailwayProjectRepository repo = global::SafeRailwayProject.Repository.SafeRailwayProjectRepository.Instance;

        static VerifyUserLoginSuccessfully instance = new VerifyUserLoginSuccessfully();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyUserLoginSuccessfully()
        {
            varUserName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyUserLoginSuccessfully Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varUserName.
        /// </summary>
        [TestVariable("2b2a12f9-7fa5-4a3f-9ce2-ca9922194bb2")]
        public string varUserName
        {
            get { return repo.varUserName; }
            set { repo.varUserName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Validate_LblWelcome(repo.SafeRailway.GeneralPage.LblWelcomeInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
