///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SafeRailwayProject.Actions.Login
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClickLoginButton recording.
    /// </summary>
    [TestModule("65489e9a-7a3d-4508-b28d-cd840ffdf9eb", ModuleType.Recording, 1)]
    public partial class ClickLoginButton : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SafeRailwayProject.Repository.SafeRailwayProjectRepository repository.
        /// </summary>
        public static global::SafeRailwayProject.Repository.SafeRailwayProjectRepository repo = global::SafeRailwayProject.Repository.SafeRailwayProjectRepository.Instance;

        static ClickLoginButton instance = new ClickLoginButton();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClickLoginButton()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClickLoginButton Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SafeRailway.LoginPage.BtnLogin' at 27;19.", repo.SafeRailway.LoginPage.BtnLoginInfo, new RecordItemIndex(0));
            repo.SafeRailway.LoginPage.BtnLogin.Click("27;19");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
