///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SafeRailwayProject.Actions.Login
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterEmailAndPassword recording.
    /// </summary>
    [TestModule("89286640-ff73-44db-96d0-d219a1465dff", ModuleType.Recording, 1)]
    public partial class EnterEmailAndPassword : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SafeRailwayProject.Repository.SafeRailwayProjectRepository repository.
        /// </summary>
        public static global::SafeRailwayProject.Repository.SafeRailwayProjectRepository repo = global::SafeRailwayProject.Repository.SafeRailwayProjectRepository.Instance;

        static EnterEmailAndPassword instance = new EnterEmailAndPassword();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterEmailAndPassword()
        {
            varUseName = "ho123@gmail.com";
            varPassWord = "12345679";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterEmailAndPassword Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUseName;

        /// <summary>
        /// Gets or sets the value of variable varUseName.
        /// </summary>
        [TestVariable("cc9ecb71-846b-4cd4-9dc5-63d359d31079")]
        public string varUseName
        {
            get { return _varUseName; }
            set { _varUseName = value; }
        }

        string _varPassWord;

        /// <summary>
        /// Gets or sets the value of variable varPassWord.
        /// </summary>
        [TestVariable("31d8affc-79d2-427e-8f2a-bd9e0c8b6bea")]
        public string varPassWord
        {
            get { return _varPassWord; }
            set { _varPassWord = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varUseName' with focus on 'SafeRailway.LoginPage.TxtUsername'.", repo.SafeRailway.LoginPage.TxtUsernameInfo, new RecordItemIndex(0));
            repo.SafeRailway.LoginPage.TxtUsername.PressKeys(varUseName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varPassWord' with focus on 'SafeRailway.LoginPage.TxtPassword'.", repo.SafeRailway.LoginPage.TxtPasswordInfo, new RecordItemIndex(1));
            repo.SafeRailway.LoginPage.TxtPassword.PressKeys(varPassWord);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
