///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SafeRailwayProject.Actions.General
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClickTab recording.
    /// </summary>
    [TestModule("c57ac0d1-7dd3-47c5-9dfb-273985f20fe1", ModuleType.Recording, 1)]
    public partial class ClickTab : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SafeRailwayProject.Repository.SafeRailwayProjectRepository repository.
        /// </summary>
        public static global::SafeRailwayProject.Repository.SafeRailwayProjectRepository repo = global::SafeRailwayProject.Repository.SafeRailwayProjectRepository.Instance;

        static ClickTab instance = new ClickTab();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClickTab()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClickTab Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varTabName.
        /// </summary>
        [TestVariable("4de1d9de-7226-4c6a-bb2b-71abcd31ca43")]
        public string varTabName
        {
            get { return repo.varTabName; }
            set { repo.varTabName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SafeRailway.GeneralPage.TabGeneral' at 16;3.", repo.SafeRailway.GeneralPage.TabGeneralInfo, new RecordItemIndex(0));
            repo.SafeRailway.GeneralPage.TabGeneral.Click("16;3");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
