///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SafeRailwayProject.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SafeRailwayProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("147f1f59-7840-4cb6-8ec5-6e759971d657")]
    public partial class SafeRailwayProjectRepository : RepoGenBaseFolder
    {
        static SafeRailwayProjectRepository instance = new SafeRailwayProjectRepository();
        SafeRailwayProjectRepositoryFolders.SafeRailwayAppFolder _saferailway;

        /// <summary>
        /// Gets the singleton class instance representing the SafeRailwayProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("147f1f59-7840-4cb6-8ec5-6e759971d657")]
        public static SafeRailwayProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SafeRailwayProjectRepository() 
            : base("SafeRailwayProjectRepository", "/", null, 0, false, "147f1f59-7840-4cb6-8ec5-6e759971d657", ".\\RepositoryImages\\SafeRailwayProjectRepository147f1f59.rximgres")
        {
            _saferailway = new SafeRailwayProjectRepositoryFolders.SafeRailwayAppFolder(this);
        }

#region Variables

        string _varUserName = "";

        /// <summary>
        /// Gets or sets the value of variable varUserName.
        /// </summary>
        [TestVariable("2b2a12f9-7fa5-4a3f-9ce2-ca9922194bb2")]
        public string varUserName
        {
            get { return _varUserName; }
            set { _varUserName = value; }
        }

        string _varTabName = "";

        /// <summary>
        /// Gets or sets the value of variable varTabName.
        /// </summary>
        [TestVariable("4de1d9de-7226-4c6a-bb2b-71abcd31ca43")]
        public string varTabName
        {
            get { return _varTabName; }
            set { _varTabName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("147f1f59-7840-4cb6-8ec5-6e759971d657")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SafeRailway folder.
        /// </summary>
        [RepositoryFolder("9817b65d-defe-459a-8cca-c14bdd88c605")]
        public virtual SafeRailwayProjectRepositoryFolders.SafeRailwayAppFolder SafeRailway
        {
            get { return _saferailway; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SafeRailwayProjectRepositoryFolders
    {
        /// <summary>
        /// The SafeRailwayAppFolder folder.
        /// </summary>
        [RepositoryFolder("9817b65d-defe-459a-8cca-c14bdd88c605")]
        public partial class SafeRailwayAppFolder : RepoGenBaseFolder
        {
            SafeRailwayProjectRepositoryFolders.LoginPageFolder _loginpage;
            SafeRailwayProjectRepositoryFolders.GeneralPageFolder _generalpage;

            /// <summary>
            /// Creates a new SafeRailway  folder.
            /// </summary>
            public SafeRailwayAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SafeRailway", "/dom[@domain='railwaysg2.somee.com']", parentFolder, 30000, null, false, "9817b65d-defe-459a-8cca-c14bdd88c605", "")
            {
                _loginpage = new SafeRailwayProjectRepositoryFolders.LoginPageFolder(this);
                _generalpage = new SafeRailwayProjectRepositoryFolders.GeneralPageFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9817b65d-defe-459a-8cca-c14bdd88c605")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9817b65d-defe-459a-8cca-c14bdd88c605")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("b47892c9-6526-4be7-9ce6-f85faa2389b1")]
            public virtual SafeRailwayProjectRepositoryFolders.LoginPageFolder LoginPage
            {
                get { return _loginpage; }
            }

            /// <summary>
            /// The GeneralPage folder.
            /// </summary>
            [RepositoryFolder("8572670f-83f6-4cee-90c9-4ded12951584")]
            public virtual SafeRailwayProjectRepositoryFolders.GeneralPageFolder GeneralPage
            {
                get { return _generalpage; }
            }
        }

        /// <summary>
        /// The LoginPageFolder folder.
        /// </summary>
        [RepositoryFolder("b47892c9-6526-4be7-9ce6-f85faa2389b1")]
        public partial class LoginPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _btnloginInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "", parentFolder, 30000, null, false, "b47892c9-6526-4be7-9ce6-f85faa2389b1", "")
            {
                _txtusernameInfo = new RepoItemInfo(this, "TxtUsername", ".//input[#'username']", ".//input[#'username']", 30000, null, "9abdd4e3-36ca-4802-99b6-4bb4930b9be6");
                _txtpasswordInfo = new RepoItemInfo(this, "TxtPassword", ".//input[#'password']", ".//input[#'password']", 30000, null, "3bcda240-883e-4691-be85-07c1504e756e");
                _btnloginInfo = new RepoItemInfo(this, "BtnLogin", ".//div[#'content']/form[@action='http://railwaysg2.somee.com/Account/Login.cshtml']//input[@title='Login']", ".//div[#'content']//input[@title='Login']", 30000, null, "4a19c203-8cac-45b3-82d8-5137d2cfeb78");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b47892c9-6526-4be7-9ce6-f85faa2389b1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b47892c9-6526-4be7-9ce6-f85faa2389b1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtUsername item.
            /// </summary>
            [RepositoryItem("9abdd4e3-36ca-4802-99b6-4bb4930b9be6")]
            public virtual Ranorex.InputTag TxtUsername
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtUsername item info.
            /// </summary>
            [RepositoryItemInfo("9abdd4e3-36ca-4802-99b6-4bb4930b9be6")]
            public virtual RepoItemInfo TxtUsernameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The TxtPassword item.
            /// </summary>
            [RepositoryItem("3bcda240-883e-4691-be85-07c1504e756e")]
            public virtual Ranorex.InputTag TxtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("3bcda240-883e-4691-be85-07c1504e756e")]
            public virtual RepoItemInfo TxtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The BtnLogin item.
            /// </summary>
            [RepositoryItem("4a19c203-8cac-45b3-82d8-5137d2cfeb78")]
            public virtual Ranorex.InputTag BtnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnLogin item info.
            /// </summary>
            [RepositoryItemInfo("4a19c203-8cac-45b3-82d8-5137d2cfeb78")]
            public virtual RepoItemInfo BtnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }
        }

        /// <summary>
        /// The GeneralPageFolder folder.
        /// </summary>
        [RepositoryFolder("8572670f-83f6-4cee-90c9-4ded12951584")]
        public partial class GeneralPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabgeneralInfo;
            RepoItemInfo _lblwelcomeInfo;

            /// <summary>
            /// Creates a new GeneralPage  folder.
            /// </summary>
            public GeneralPageFolder(RepoGenBaseFolder parentFolder) :
                    base("GeneralPage", "", parentFolder, 30000, null, false, "8572670f-83f6-4cee-90c9-4ded12951584", "")
            {
                _tabgeneralInfo = new RepoItemInfo(this, "TabGeneral", ".//div[#'menu']/ul//span[@innertext=$varTabName]", "", 30000, null, "231eea74-33ab-4926-a450-b95e238156ef");
                _lblwelcomeInfo = new RepoItemInfo(this, "LblWelcome", ".//div[#'banner']/?/?/strong[@innertext>'']", ".//div[#'banner']/?/?/strong[@innertext>'']", 30000, null, "3578dfb1-122e-4c9a-afef-bfb0b924a0d2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8572670f-83f6-4cee-90c9-4ded12951584")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8572670f-83f6-4cee-90c9-4ded12951584")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TabGeneral item.
            /// </summary>
            [RepositoryItem("231eea74-33ab-4926-a450-b95e238156ef")]
            public virtual Ranorex.SpanTag TabGeneral
            {
                get
                {
                    return _tabgeneralInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TabGeneral item info.
            /// </summary>
            [RepositoryItemInfo("231eea74-33ab-4926-a450-b95e238156ef")]
            public virtual RepoItemInfo TabGeneralInfo
            {
                get
                {
                    return _tabgeneralInfo;
                }
            }

            /// <summary>
            /// The LblWelcome item.
            /// </summary>
            [RepositoryItem("3578dfb1-122e-4c9a-afef-bfb0b924a0d2")]
            public virtual Ranorex.StrongTag LblWelcome
            {
                get
                {
                    return _lblwelcomeInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The LblWelcome item info.
            /// </summary>
            [RepositoryItemInfo("3578dfb1-122e-4c9a-afef-bfb0b924a0d2")]
            public virtual RepoItemInfo LblWelcomeInfo
            {
                get
                {
                    return _lblwelcomeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
